xset r rate 300 50

xrdb ~/.config/x11/xresources
picom -b

(xss-lock \
env \
XSECURELOCK_AUTH_FOREGROUND_COLOR=black \
XSECURELOCK_AUTH_BACKGROUND_COLOR=white \
XSECURELOCK_FONT="Atkinson Hypermono" \
XSECURELOCK_SHOW_DATETIME=1 \
xsecurelock & ) #screen locker

dwm