xset r rate 300 50

xrdb ~/.config/x11/xresources

start_me="picom sxhkd dunst pipewire pipewire-pulse dwmblocks blueman-applet"
for program in $start_me; do
	pidof -xs "$program" || setsid "$program" &
done > /dev/null 2>&1

(xss-lock \
env \
XSECURELOCK_AUTH_FOREGROUND_COLOR=black \
XSECURELOCK_AUTH_BACKGROUND_COLOR=white \
XSECURELOCK_FONT="Atkinson Hypermono" \
XSECURELOCK_SHOW_DATETIME=1 \
xsecurelock & ) #screen locker

ssh-agent dwm
